### ISSUE TITLE
The frames of N-UCLA

### ISSUE THREAD

**Issue by punknownq** [srijandas07/P-I3D#1]
Thank you for your great job! Could you tell me how many frames per video of the N-UCLA do you use?

**Comment by srijandas07** [comment]
@punknownq Thank you for your interest in our work!
The no. of frames per video used for NUCLA is also 64. Though the length of these videos are less than NTU, but you can use the NTU Loader which allows you to loop through the video or copy the last frames.

**Comment by punknownq** [comment]
Thank you for your reply. I have read your paper. “Similar to [32], we cut the videos into sub-sequences of 20 and 5 frames and sample sub-sequences for NTU and N-UCLA respectively.” In this paragraph, "sub-sequences" mean?

**Comment by srijandas07** [comment]
@punknownq, the quoted comment is made for the Pose input to the attention network. For NUCLA, we uniformly sample 5 frames (corresponding 3D poses) from a video.
