### ISSUE TITLE
Image saperation.

### ISSUE THREAD

**Issue by Dkoutrintzes** [srijandas07/P-I3D#2]
Hello, I'm trying to break the image into the three sub-images (left hand, right hand, and body) I using the skeleton data to find the locations on the RGB images but when I convert the skeleton data to image coordinates there a deviation, how did you break the RGB images?
Thank you for your time.

**Comment by srijandas07** [comment]
Hi @Dkoutrintzes,
Are you using the 2D skeleton data from Kinect? Then transforming the coordinates using the calibration parameters should work. In my case, I prefer using the 2D poses extracted from algorithms like OpenPose. You do not need to perform any transformation in that case.

**Comment by Dkoutrintzes** [comment]
Thank you for the answer, I didn't have the 2d data from Kinect, i had a preprocessed file that had only the skeleton coordinates, i redownload the NTU dataset and find the 2d that you are referring, again thank you for the response.
